---
- name: ensure ghost group exists
  group: name=ghost state=present system=yes

- name: ensure ghost user exists
  user: name=ghost group=ghost createhome=yes home={{ blog_path }} shell=/bin/false state=present system=yes

- name: download ghost
  command: wget https://ghost.org/zip/ghost-latest.zip -P /tmp creates=/tmp/ghost-latest.zip

- name: extract ghost
  unarchive: src=/tmp/ghost-latest.zip dest={{ blog_path }} copy=no creates={{ blog_path }}/core

- name: configure ghost
  template: src=config.js.j2 dest={{ blog_path }}/config.js
  notify: restart blog

- name: npm install
  command: npm install --production chdir={{ blog_path }} creates={{ blog_path }}/node_modules
  notify: restart blog

- name: npm install ghost s3 storage
  command: npm install ghost-s3-storage chdir={{ blog_path }} creates={{ blog_path }}/node_modules/ghost-s3-storage
  notify: restart blog

- name: create ghost s3 storage directory
  file: path={{ blog_path }}/content/storage/ghost-s3 state=directory recurse=yes

- name: configure ghost s3 storage
  template: src=s3.js.j2 dest={{ blog_path }}/content/storage/ghost-s3/index.js
  notify: restart blog

- name: install theme
  git: repo=https://github.com/phpsw/ghostium.git dest={{ blog_path }}/content/themes/ghostium
  notify: restart blog

- command: "chown -R ghost:ghost {{ blog_path }}"
  notify: restart blog

- name: configure supervisor
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/blog.conf
  notify: reread supervisor

- supervisorctl: name=blog state=started
