#!/usr/bin/env php
<?php

set_time_limit(0);

require_once __DIR__ . '/../vendor/autoload.php';

$app = require_once __DIR__ . '/app.php';

$app['cli'] = true;

$app->register(new Knp\Provider\ConsoleServiceProvider, array(
    'console.name' => 'PHPSW',
    'console.version' => '0.1.0',
    'console.project_directory' => __DIR__ . '/..'
));

$console = $app['console'];
$console->add(new PHPSW\Command\MeetupCommand);
$console->add(new PHPSW\Command\TwitterCommand);

if ($app['env'] == 'dev') {
    $console->add(new PHPSW\Command\Redis\DumpCommand);
    $console->add(new PHPSW\Command\Redis\RestoreCommand);
}

$console->run();
